---
abstract: 'Perl bindings to Foo via XS'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Alien::Foo: 0
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Foo-XS
provides:
  Foo::XS:
    file: lib/Foo/XS.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
